### PR TITLE
Review installation of modules and local dependencies

### PR DESCRIPTION
**Pull request by jomrazek**

### CODE REVIEW

**Comment by jomrazek** [comment]
@alexcreasy @matedo1 @DnsZhou guys can we have a discussion about installation of this library. I don't know if it's just me but if I download fresh code from github only parent module gets installed, I need to run npm install in every module then. So I created postinstall script in main module to install all. Running install in child modules also mean there is problem with unpublished dependencies and I always need to link them, which is problem for jenkins job I'm creating so given they are always there I change dependency style from version to file source. Everything seems to be working now for me so now questions, is there something wrong with this approach? do you have same problems and we just forgot about them because we done it once while setting up project?

**Comment by matedo1** [comment]
Hi @jomrazek , 

(I assume all dependencies and your local Node + NPM environment are up-to-date, right?)

my understanding is that 
```
$ lerna bootstrap
```
should be the solution for us? Based on the [lerna documentation - bootstrap command](https://github.com/lerna/lerna/tree/main/commands/bootstrap#usage):
```
Bootstrap the packages in the current Lerna repo. Installs all of their dependencies and links any cross-dependencies.
```

But I can see existing issues (including workaround): 
 - https://github.com/lerna/lerna/issues/1457
 - https://github.com/lerna/lerna/issues/2352

Did you try play around this command?

@alexcreasy do you have any experience with Jozo's issue while working with lerna?

**Comment by jomrazek** [comment]
@matedo1 will try, don't know much about lerna so we might just update documentation on this package

**Comment by matedo1** [comment]
Hi @jomrazek were you able to find out some final solution for this one?

**Comment by porkus1990** [comment]
I'd be interested in this, too.
Facing the same issue with lerna 4.0.0

**Comment by jomrazek** [comment]
@porkus1990 we ended up with this solution https://github.com/project-ncl/pnc-js-libs/pull/19/files

**Pull request closed without merging**
